# [NumPy ](http://www.numpy.org)   (Numerical Python)



![imagen.png](numpy.jpeg)

NumPy es una biblioteca Python para vectores y matrices.

El antecedente de NumPy, es la biblioteca Numeric, originalmente realizada por Jim Hugunin y otros desarrolladores. 

En 2005, Travis Oliphant crea NumPy incorporando características de Numarray en NumPy con algunas modificaciones. 

 


Biblioteca para el análisis de datos. 

Tiene funcionalidad que permite manejo de:

* ndarray : matriz multidimensional 
* Funciones matemáticas 
* Álgebra lineal 
* Herramientas para leer/escribir matrices en disco
* Herramientas para integrar código de C, C++ y Fortran

Se incorpora la biblioteca matplotlib

In [1]:
%matplotlib inline

In [2]:
from __future__ import division
from numpy.random import randn
import numpy as np
np.set_printoptions(precision=4, suppress=True)

### NumPy ndarray:  
Objeto N-dimensional, el cual es rápido y flexible. 

Esta estructura puede contener grandes conjuntos de datos en Python

In [3]:
### Creación de un arreglo de 3x4, 
### Es decir, una matriz de 3 renglones y 4 columnas de valores aleatorios
data = randn(3, 4)
data

array([[ 0.318 , -1.0225, -0.3382,  1.1196],
       [-0.1652,  1.4867,  0.2913, -0.89  ],
       [-0.0257,  1.7809, -0.0795, -1.3179]])

In [4]:
data.shape

(3, 4)

In [5]:
data.dtype

dtype('float64')

In [6]:
print ("La dimensión de la matriz es:  " + str(data.shape))
print ("El tipo de las entradas de la matriz es: " + str(data.dtype))

La dimensión de la matriz es:  (3, 4)
El tipo de las entradas de la matriz es: float64


In [7]:
### Multiplicación de cada elemento de la matriz por un escalar
data * 10

array([[  3.1799, -10.2246,  -3.3816,  11.1958],
       [ -1.6524,  14.8675,   2.9126,  -8.8998],
       [ -0.2566,  17.8093,  -0.7954, -13.1791]])

In [8]:
### Suma de matrices
### Cada una de las matrices debe ser de la MISMA DIMENSIÓN
print (data + data)

[[ 0.636  -2.0449 -0.6763  2.2392]
 [-0.3305  2.9735  0.5825 -1.78  ]
 [-0.0513  3.5619 -0.1591 -2.6358]]


In [9]:
### Creación de una lista de valores
data1 = [6, 7.5, 8, 0, 1]
data1

[6, 7.5, 8, 0, 1]

In [10]:
### Creación de un arreglo con datos de entrada, que se indican como una lista de valores

arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [11]:
arr1.dtype

dtype('float64')

In [12]:
#Anidamos listas de datos
data2 = [[[1, 2], [3, 4], [10,11]], [[5, 6], [7, 8], [12,13]]]
data2

[[[1, 2], [3, 4], [10, 11]], [[5, 6], [7, 8], [12, 13]]]

In [13]:
### Generamos un arreglo
arr2 = np.array(data2)
arr2

array([[[ 1,  2],
        [ 3,  4],
        [10, 11]],

       [[ 5,  6],
        [ 7,  8],
        [12, 13]]])

In [14]:
arr2.shape

(2, 3, 2)

Esto puede pensarse como un archivo Excel, con 2 hojas. 

En cada hoja una matriz 3x2. 

Es decir de 3 renglones con 2 columnas

In [15]:
#Vemos cuantas "capas" tenemos, es decir, cuantos subarreglos tenemos
arr2.ndim

3

In [16]:
### Creacion de un vector  solo con ceros
VectorCeros = np.zeros(10)
VectorCeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
VectorCeros.shape

(10,)

In [18]:
### Creacion de un arreglo solo con ceros
### Creacion de 3 renglones y 6 columnas con ceros
ArregloCeros = np.zeros((3, 6))
ArregloCeros

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [19]:
ArregloCeros.shape

(3, 6)

Definimos el arreglo de la siguiente manera: 
\begin{matrix} 
a_{11} & a_{12} & \ldots &a_{1n} \\
\vdots & & \ddots & \vdots  \\
a_{m1} & a_{m2} & \ldots & a_{mn} 
\end{matrix}

In [20]:
### Creacion de un arreglo (m,n) con valores aleatorios de tipo entero
### Ejemplo m= 2 renglones y n= 3 columnas
###
ArregloAleatorioEntero = np.empty([2, 3], dtype=np.int32)
ArregloAleatorioEntero

array([[         0, 1072168960,          0],
       [1072168960,          0,          0]], dtype=int32)

In [21]:
ArregloAleatorioEntero.ndim

2

In [22]:
ArregloAleatorioFlotante = np.empty([2, 3], dtype=np.float64)
ArregloAleatorioFlotante

array([[3.3103e-033, 4.5749e-071, 3.4570e-086],
       [3.3576e-143, 6.0143e+175, 6.9389e+218]])

In [23]:
ArregloAleatorioFlotante.ndim

2

In [24]:
### Creación de un arreglo con 15 elementos, 
### con los primeros 15 números, empezando desde 0
misprimerosdigitos = np.arange(15)
misprimerosdigitos

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [25]:
misprimerosdigitos.shape

(15,)

In [26]:
misprimerosdigitos.ndim

1

### Data Types para ndarrays
Podemos escoger el tipo de dato que queremos 

In [27]:
#Podemos indicarle el tipo desde el principio
arreglo1 = np.array([1, 2, 3], dtype=np.float64)

print ("tipo de arrglo1 es " + str(arreglo1.dtype))
arreglo1

tipo de arrglo1 es float64


array([1., 2., 3.])

In [28]:
arreglo1.ndim

1

In [29]:
arreglo2 = np.array([1, 2, 3], dtype=np.int32)
print ("tipo de arreglo2 es " + str(arreglo2.dtype))
arreglo2

tipo de arreglo2 es int32


array([1, 2, 3], dtype=int32)

In [30]:
#Una vez creado podemos cambiarle el tipo
arreglo3 = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arreglo3



array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [31]:
arreglo3.dtype

dtype('float64')

In [32]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings 


array([b'1.25', b'-9.6', b'42'], dtype='|S4')

In [33]:
numeric_strings.dtype

dtype('S4')

In [34]:
empty_uint32 = np.empty(8, dtype='u4')
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

In [35]:
empty_uint32.dtype

dtype('uint32')

### Operacios entre arreglos y escalares

Podemos hacer operaciones con los arreglos

In [36]:
arr = np.array([[1., 2., 3.], [4., 5., 6]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [37]:
arr.shape

(2, 3)

In [38]:
### Arreglo Inverso Multiplicativo
### Cada elemento se define 1/elemento
### 
arrInverso = 1 / arr
arrInverso

array([[1.    , 0.5   , 0.3333],
       [0.25  , 0.2   , 0.1667]])

In [39]:
arrInverso.shape

(2, 3)

In [40]:
#### Multiplicacion de arreglo por otro
#### Cada elemento de un arreglo se multiplica por correspondiente en el otro arreglo
arr * arrInverso

array([[1., 1., 1.],
       [1., 1., 1.]])

In [41]:
### Potencias multiplicativas de arreglos
###  Se multiplica cada elemento de arr por cada elemento de arr
arr ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

### Indices y particiones de arreglos

In [42]:
arreglo = np.array([0,1,2,3,4,10,12,14])
arreglo

array([ 0,  1,  2,  3,  4, 10, 12, 14])

In [43]:
arreglo.shape

(8,)

In [44]:
#### Extraccion  del 0 elemento de la lista, empezando desde 0
arreglo[0]

0

In [45]:
#### Extraccion  del 5 elemento de la lista, empezando desde 0
arreglo[5]

10

In [46]:
#### Extraccion  del 7 elemento de la lista, empezando desde 0
arreglo[7]

14

In [47]:
arreglo

array([ 0,  1,  2,  3,  4, 10, 12, 14])

In [48]:
###Tomamos del 5° lugar al 7° lugar,
### La notacion [inicio:final] considera hasta antes sin incluir el final
arreglo[5:8]

array([10, 12, 14])

In [49]:
#Podemos aplicarlo las veces que sea necesario
arr2= arreglo[5:8]
arr2[0]

10

In [50]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
arr2d[2]

array([7, 8, 9])

In [52]:
#Podemos hacerlo al mismo tiempo
arr2d[2][0]

7

In [53]:
arr2d[2, 0]

7

In [54]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [55]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
#Podemos cambiar los valores de las entradas
old_values = arr3d[0].copy()
old_values

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [58]:
arr3d[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [59]:
arr3d[1, 0]

array([7, 8, 9])

In [60]:
arreglo2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arreglo2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
arreglo2d.shape

(3, 3)

In [62]:
subarreglo1 = arreglo2d[:2]
subarreglo1

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
subarreglo2 = arreglo2d[1,:2]

In [64]:
subarreglo2

array([4, 5])

In [65]:
subarreglo1 = arr2d[1, :2]
subarreglo1

array([4, 5])

In [66]:
subarreglo2 = arr2d[2, :1]
subarreglo2

array([7])

In [67]:
subarreglo3 = arr2d[:, :1]
subarreglo3

array([[1],
       [4],
       [7]])

In [68]:
subarreglo4 = arr2d[:, :2]
subarreglo4

array([[1, 2],
       [4, 5],
       [7, 8]])

In [69]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

### Indices con Booleanos 

In [70]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [71]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [72]:
data = randn(7, 4)
data

array([[-0.2798,  0.4399, -0.3656,  1.5746],
       [ 1.3565, -1.3158, -0.0928, -0.3586],
       [ 0.2695,  1.3831, -0.8823, -1.6937],
       [ 0.84  , -0.3124,  1.5086,  1.1323],
       [ 0.7623,  0.6724, -0.3362, -0.1393],
       [ 1.5824, -0.5451,  1.9022, -0.4677],
       [ 1.1004,  0.5667, -0.9953, -0.7781]])

In [73]:
#Elegimos en que lugar está el nombre y después cortamos.
data[names == 'Bob', 2:]


array([[-0.3656,  1.5746],
       [ 1.5086,  1.1323]])

In [74]:
#Elegimos en que NO aparece el nombre 
names != 'Bob'


array([False,  True,  True, False,  True,  True,  True])

In [75]:
data[(names == 'Bob')]

array([[-0.2798,  0.4399, -0.3656,  1.5746],
       [ 0.84  , -0.3124,  1.5086,  1.1323]])

In [76]:
#Podemos combinar más de uno
mask = (names == 'Bob') | (names == 'Will')
mask


array([ True, False,  True,  True,  True, False, False])

In [77]:
data[mask]

array([[-0.2798,  0.4399, -0.3656,  1.5746],
       [ 0.2695,  1.3831, -0.8823, -1.6937],
       [ 0.84  , -0.3124,  1.5086,  1.1323],
       [ 0.7623,  0.6724, -0.3362, -0.1393]])

In [78]:
#Podemos cambiar todas las entradas que cumplan algo
#en este caso convertimos a cero todas las entradas menores a cero
data[data < 0] = 0
data

array([[0.    , 0.4399, 0.    , 1.5746],
       [1.3565, 0.    , 0.    , 0.    ],
       [0.2695, 1.3831, 0.    , 0.    ],
       [0.84  , 0.    , 1.5086, 1.1323],
       [0.7623, 0.6724, 0.    , 0.    ],
       [1.5824, 0.    , 1.9022, 0.    ],
       [1.1004, 0.5667, 0.    , 0.    ]])

In [79]:
data[names != 'Joe'] = 7
data

array([[7.    , 7.    , 7.    , 7.    ],
       [1.3565, 0.    , 0.    , 0.    ],
       [7.    , 7.    , 7.    , 7.    ],
       [7.    , 7.    , 7.    , 7.    ],
       [7.    , 7.    , 7.    , 7.    ],
       [1.5824, 0.    , 1.9022, 0.    ],
       [1.1004, 0.5667, 0.    , 0.    ]])